version: '3.1'
services:
  mysql:
    container_name: mysql        
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 02580258@lL
    ports:
      - '3306:3306'
    volumes:
      - /usr/local/docker/mysql/data:/var/lib/mysql

